project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('spending/', include('spending.urls')),
]

project/spending/urls.py
from django.urls import path

from . import views

app_name = 'spending'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('postlogin', views.postlogin, name='postlogin'),
    path('createUser', views.CreateUserView.as_view(), name='createUser'),
    path('postCreateUser', views.postCreateUser, name='postCreateUser'),
    path('user/<int:pk>', views.UserView.as_view(), name='user'),
    path('addReceipt/<int:user_id>', views.createReceipt, name='createReceipt'),
    path('postCreateReceipt/<int:user_id>', views.postCreateReceipt, name='postCreateReceipt'),
    path('addStyle/<int:user_id>', views.addStyle, name='addStyle')
]

project/spending/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=50)
    name = models.CharField(max_length=200)
    ssn = models.CharField(max_length=11)
    address = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    nameStyle = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.name

class Shop(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Receipt(models.Model):
    totalSum = models.DecimalField(decimal_places=2, max_digits=10)
    receiptDate = models.DateField('receipt date')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.totalSum)

project/spending/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import User, Receipt, Shop

class IndexView(generic.TemplateView):
    template_name = 'spending/index.html'

class LoginView(generic.TemplateView):
    template_name = 'spending/login.html'

class CreateUserView(generic.TemplateView):
    template_name = 'spending/createUser.html'

class UserView(generic.DetailView):
    model = User
    template_name = 'spending/user.html'

def createReceipt(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    shops = Shop.objects.all()
    return render(request, 'spending/createReceipt.html', {'user': user, 'shops': shops})

def postCreateReceipt(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    shop = get_object_or_404(Shop, pk=request.POST['shop'])
    totalSum = request.POST['sum']
    date = request.POST['date']
    receipt = Receipt(totalSum = totalSum, receiptDate = date, user = user, shop = shop)
    receipt.save()
    return HttpResponseRedirect(reverse('spending:user', args=(user_id,)))

def postlogin(request):
    username = request.POST['username']
    password = request.POST['password']
    query = "SELECT * FROM spending_user WHERE username='%s' AND password='%s'" % (username, password)
    userSet = User.objects.raw(query)
    try:
        user = userSet[0]
    except:
        return render(request, 'spending/login.html', {'error_message': 'Wrong username or password!'})
    else:
        return HttpResponseRedirect(reverse('spending:user', args=(user.id,)))

def postCreateUser(request):
    if request.POST['password'] != request.POST['passwordRepeat']:
        return render(request, 'spending/createUser.html', {'error_message': 'Passwords don\'t match'})
    try:
        username = request.POST['username']
        query = "SELECT * FROM spending_user WHERE username='%s'" % username
        userSet = User.objects.raw(query)
        user = userSet[0]
    except:
        user = User(
            username=request.POST['username'],name=request.POST['name'],ssn=request.POST['ssn'],address=request.POST['address'],password=request.POST['password']
        )
    else:
        return render(request, 'spending/createUser.html', {'error_message': 'Username already exists'})

    user.save()
    return HttpResponseRedirect(reverse('spending:login'))

def addStyle(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    user.nameStyle = request.POST['style']
    user.save()
    return HttpResponseRedirect(reverse('spending:user', args=(user.id,)))




project/spending/templates/spending/createReceipt.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Spending app</title>
        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'spending/style.css' %}">
    </head>
    <body>
        <h1>Add a new recipt!</h1>
        <h4>Fill in the details below</h4>
        {% if error_message %}<p class="error-message">{{ error_message }}</p>{% endif %}
        <h3>{{ user.name }}</h3>
        
        <form action="{% url 'spending:postCreateReceipt' user.id %}" method="POST">
            {% csrf_token %}
            <label for="shop">Shop</label>
            <select name="shop">
                {% for shop in shops %}
                    <option value="{{shop.id}}">{{ shop.name }}</option>
                {% endfor %}
            </select>
            <label for="date">Date</label>
            <input type="date" name="date"  required>
            <label for="sum">Total sum</label>
            <input type="number" min=0 step=0.01 name="sum" required>
            <input type="submit" value="Add receipt">
        </form>
    </body>
</html>

project/spending/templates/spending/createUser.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Spending app</title>
        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'spending/style.css' %}">
    </head>
    <body>
        <h1>Create a new user!</h1>
        <h4>Fill in your details below</h4>
        {% if error_message %}<p class="error-message">{{ error_message }}</p>{% endif %}
        <form action="{% url 'spending:postCreateUser' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" required>
            <label for="name">Name</label>
            <input type="text" name="name" required>
            <label for="ssn">SSN</label>
            <input type="text" name="ssn" required>
            <label for="address">Address</label>
            <input type="text" name="address" required>
            <label for="password">Password</label>
            <input type="password" name="password">
            <label for="passwordRepeat">Password again</label>
            <input type="password" name="passwordRepeat">
            <input type="submit" value="Create user">
        </form>
    </body>
</html>

project/spending/templates/spending/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Spending app</title>
        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'spending/style.css' %}">
    </head>
    <body>
        <h1>Spending App</h1>
        <h4>Log in, or create a user if you don't already have one!</h4>
        <button onclick="location.href='/spending/login';">LOG IN</button>
        <button onclick="location.href='/spending/createUser';">CREATE NEW USER</button>
    </body>
</html>

project/spending/templates/spending/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Spending app</title>
        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'spending/style.css' %}">
    </head>
    <body>
        <h1>Log in!</h1>
        <h4>Fill in your user credentials below</h4>
        {% if error_message %}<p class="error-message">{{ error_message }}</p>{% endif %}
        <form action="{% url 'spending:postlogin' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username">
            <label for="password">Password</label>
            <input type="password" name="password">
            <input type="submit" value="Log in">
        </form>
    </body>
</html>

project/spending/templates/spending/user.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Spending app</title>
        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'spending/style.css' %}">
    </head>
    <body>
        <h1 style={{ user.nameStyle }}>{{ user.name }}</h1>
        <h3>{{ user.ssn }}</h3>
        <h3>{{ user.address }}</h3>
        <h3>Add custom style to your username, e.g. "color:red"</h3>
        <form action="{% url 'spending:addStyle' user.id %}" method="POST">
            {% csrf_token %}
            <input type="text" name="style">
            <input type="submit" value="Add style!">
        </form>
        <h4>Check your previous receipts or add a new one</h4>

        {% if error_message %}<p class="error-message">{{ error_message }}</p>{% endif %}
        <button onclick="location.href='/spending/addReceipt/{{ user.id }}';">Add new receipt</button>
        <h4>Previous receipts:</h4>
        <div class="container">
            <ul>
                {% for receipt in user.receipt_set.all %}
                    <li>{{ receipt.shop }} {{ receipt.receiptDate }}, sum: {{ receipt.totalSum }}€</li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>